from django.conf.urls import url
from . import views

urlpatterns = [
    # event draft views
    url(r'^events$',
                                        views.EventListView.as_view(),
                                        name='event_list1'),
    url(r'^events/draft/(?P<year>\d{4})/(?P<order>[-\w]*)$',
                                        views.event_draft_list  ,
                                        name='event_draft_list'  ),
    url(r'^events_ephem/draft/(?P<year>\d{4})/(?P<order>[-\w]*)$',
                                        views.event_ephem_draft_list  ,
                                        name='event_ephem_draft_list'  ),
    url(r'^events_ephem/draft/(?P<year>\d{4})/(?P<eventtype>[a-zA-Z0-9_]+)$',
                                        views.event_ephem_type_draft_list  ,
                                        name='event_ephem_type_draft_list'  ),
    url(r'^events_ephem/(?P<year>\d{4})/(?P<order>[-\w]*)$',
                                        views.event_ephem_list  ,
                                        name='event_ephem_list'  ),
    url(r'^test/(?P<year>\d{4})$',
                                        views.test_list  ,
                                        name='test_list'  ),
    url(r'^test_ephem/(?P<year>\d{4})$',
                                        views.test_ephem_list  ,
                                        name='test_ephem_list'  ),
#   url(r'^events/(?P<year>\d{4})/(?P<order>[-\w]*)$',
#                                       views.event_list       ,
#                                       name='event_list'       ),
    url(r'^aux_events/(?P<year>\d{4})/(?P<order>[-\w]*)$',
                                        views.aux_event_list       ,
                                        name='aux_event_list'       ),
    url(r'^events/cancel_list$',
                                        views.event_cancel_list,
                                        name='event_cancel_list'),
    url(r'^events/cancel/(?P<event_id>\d+)$',
                                        views.event_cancel,
                                        name='event_cancel'),
    url(r'^(?P<pk>\d+)',                views.event_detail,
                                        name='event_detail'),
    url(r'^search$', views.search,
                     name='event-search'),
    url(r'^period=(?P<period>\d{6}-\d{6})/loc=(?P<location>\d*)/event_type=(?P<event_type>\d*)',
                     views.event_list,
                     name='event_list')

]
